### ISSUE TITLE
Message type "caffe.LayerParameter" has no field named "video_data_param".

### ISSUE THREAD

**Issue by sfzhoujob** [chuckcho/video-caffe#49] opened 2016-10-10 07:39 UTC
when run c3d_ucf101_train_test.prototxt, I got a error, how to solve it?

I1010 15:36:45.109537  2351 solver.cpp:91] Creating training net from net file: examples/c3d_ucf101/c3d_ucf101_train_test.prototxt
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 10:20: Message type "caffe.LayerParameter" has no field named "video_data_param".
F1010 15:36:45.109596  2351 upgrade_proto.cpp:79] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: examples/c3d_ucf101/c3d_ucf101_train_test.prototxt
**\* Check failure stack trace: ***
    @     0x7fbf8060bdaa  (unknown)
    @     0x7fbf8060bce4  (unknown)
    @     0x7fbf8060b6e6  (unknown)
    @     0x7fbf8060e687  (unknown)
    @     0x7fbf809d3efe  caffe::ReadNetParamsFromTextFileOrDie()
    @     0x7fbf80b1370b  caffe::Solver<>::InitTrainNet()
    @     0x7fbf80b147dc  caffe::Solver<>::Init()
    @     0x7fbf80b14b0a  caffe::Solver<>::Solver()
    @     0x7fbf80b07893  caffe::Creator_SGDSolver<>()
    @           0x40eb6e  caffe::SolverRegistry<>::CreateSolver()
    @           0x407d4b  train()
    @           0x40589c  main
    @     0x7fbf7f617f45  (unknown)
    @           0x40610b  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by chuckcho** [comment] 2016-10-31 17:14
are you still having this issue? if it's built properly, it should be able to parse "video_data_param".

**Comment by akilawickey** [comment] 2016-12-22 06:59
ubuntu@tegra-ubuntu:/mnt/data/Test_AA/caffe-ssd/ssd-tx1$ /mnt/data/Test_AA/caffe-ssd/build/tools/caffe test --model="/mnt/data/Test_AA/jetson-inference/build/aarch64/bin/alexnet.prototxt" --weights="/mnt/data/Test_AA/jetson-inference/build/aarch64/bin/bvlc_alexnet.caffemodel" --iterations="400000" --gpu 0
I1222 06:59:29.603371 11619 caffe.cpp:270] Use GPU with device ID 0
I1222 06:59:29.676323 11619 caffe.cpp:274] GPU device name: NVIDIA Tegra X1
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 6:20: Message type "caffe.LayerParameter" has no field named "video_data_param".
F1222 06:59:30.582382 11619 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /mnt/data/Test_AA/jetson-inference/build/aarch64/bin/alexnet.prototxt
*** Check failure stack trace: ***
    @       0x7f9a991718  google::LogMessage::Fail()
    @       0x7f9a993614  google::LogMessage::SendToLog()
    @       0x7f9a991290  google::LogMessage::Flush()
    @       0x7f9a993eb4  google::LogMessageFatal::~LogMessageFatal()
    @       0x7f9ac55274  caffe::ReadNetParamsFromTextFileOrDie()
    @       0x7f9ac23a9c  caffe::Net<>::Net()
    @           0x409f00  test()
    @           0x408330  main
    @       0x7f9a5438a0  __libc_start_main
Aborted

**Comment by chuckcho** [comment] 2016-12-22 16:29
@sfzhoujob if you resolved this issue, can you help @akilawickey? I can't reproduce this error.  `video_param_layer` is defined in https://github.com/chuckcho/video-caffe/blob/master/src/caffe/proto/caffe.proto#L410

**Comment by MohammadMoradi** [comment] 2017-07-17 07:08
Hi, I exactly have the same problem. Is there any solution?

```
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 10:20: Message type "caffe.LayerParameter" has no field named "video_data_param".
F0717 11:35:31.909482 18582 upgrade_proto.cpp:79] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: examples/c3d_ucf101/c3d_ucf101_train_test.prototxt
*** Check failure stack trace: ***
    @     0x7f293477d5cd  google::LogMessage::Fail()
    @     0x7f293477f433  google::LogMessage::SendToLog()
    @     0x7f293477d15b  google::LogMessage::Flush()
    @     0x7f293477fe1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f2934ec2091  caffe::ReadNetParamsFromTextFileOrDie()
    @     0x7f2934e6289b  caffe::Solver<>::InitTrainNet()
    @     0x7f2934e63c87  caffe::Solver<>::Init()
    @     0x7f2934e64043  caffe::Solver<>::Solver()
    @     0x7f2934d049e5  caffe::Creator_SGDSolver<>()
    @           0x40ba35  train()
    @           0x4086f8  main
    @     0x7f29331cf830  __libc_start_main
    @           0x408e69  _start
    @              (nil)  (unknown)
Aborted (core dumped)

```

**Comment by chuckcho** [comment] 2017-09-21 00:35
Closing as it's not reproducible

**Closed by chuckcho** 2017-09-21 00:35 UTC
Labels: help wanted, wontfix
