### ISSUE TITLE
check_data_and_model.py will output the same result when input different images  via "./c3d_ucf101_iter_38000.caffemodel" 

### ISSUE THREAD

**Issue by junmuzi** [chuckcho/video-caffe#98] opened 2017-04-26 02:08 UTC
I hit a issue when use your github code. The output of  check_data_and_model.py is the same all the time using model "./c3d_ucf101_iter_38000.caffemodel" when I input different images(I have tried fish-bike.jpg and cat.jpg). I am so surprised and puzzled. Maybe I have got some mistakes anywhere, could anyone give me some suggestion? Thanks.

The follow is my debug info(based on 25bc6d):

(Pdb) p output_prob
array([ 0.00580123,  0.00344231,  0.00512505,  0.02758851,  0.02166136,
        0.0047916 ,  0.00347026,  0.02464976,  0.00655003,  0.00455923,
        0.01620403,  0.00231314,  0.00538909,  0.01927903,  0.00329624,
        0.00759618,  0.00291226,  0.00790412,  0.00663601,  0.00576234,
        0.00265791,  0.06774281,  0.00394197,  0.00217366,  0.0103282 ,
        0.01745262,  0.00499696,  0.00596806,  0.01204872,  0.01465816,
        0.00390601,  0.0154008 ,  0.00425976,  0.00915863,  0.01411434,
        0.00991541,  0.00278897,  0.01102778,  0.00692579,  0.01100748,
        0.00544623,  0.01335799,  0.00461721,  0.00599697,  0.00970814,
        0.00304217,  0.00306839,  0.00074699,  0.02649253,  0.00471338,
        0.00893008,  0.00684513,  0.00769747,  0.01527166,  0.00784316,
        0.00401985,  0.00626187,  0.01174736,  0.00355275,  0.00587889,
        0.00333939,  0.00414828,  0.00603733,  0.00444678,  0.00319782,
        0.00324162,  0.00606149,  0.0392826 ,  0.0051594 ,  0.00588619,
        0.00756048,  0.01787155,  0.00951777,  0.02192619,  0.02281141,
        0.00852187,  0.0024029 ,  0.00562544,  0.00997402,  0.02348322,
        0.02809488,  0.01101367,  0.01037497,  0.00545539,  0.00268822,
        0.01033187,  0.00794003,  0.00903882,  0.00927738,  0.00494286,
        0.00861302,  0.00618246,  0.01118466,  0.0049173 ,  0.00323196,
        0.00650915,  0.01022164,  0.04497042,  0.00473391,  0.01566175,
        0.00347585], dtype=float32)
(Pdb) p output_prob.argmax()
21

**Comment by junmuzi** [comment] 2017-04-26 14:02
I have used mnist net test this code again, do not hit this issue. So I think this issue is due to the c3d_ucf101_train_test.prototxt. The parameter of the network setting is not appropriate.

**Comment by chuckcho** [comment] 2017-09-21 17:27
sorry for the delayed response. with the latest code and model, I can't reproduce this. I believe this issue has been taken care of.

**Comment by chuckcho** [comment] 2017-09-21 17:27
closing as such

**Closed by chuckcho** 2017-09-21 17:27 UTC
