### ISSUE TITLE
try "date -d @1501766073" if you are using GNU date  when shuttling data

### ISSUE THREAD

**Issue by MengXinChengXuYuan** [chuckcho/video-caffe#100] opened 2017-08-03 14:03 UTC
Hi I got this error when the data layer is shuttling data
I know its something with the random seed generation, but how can I fix it ?

```
I0803** 15:14:33.233795  2524 video_data_layer.cpp:53] Shuffling data
I0803 15:14:33.233801  2524 video_data_layer.cpp:58] A total of 0 video chunks.
*** Aborted at 1501766073 (unix time) try "date -d @1501766073" if you are using GNU date ***
PC: @     0x7f4a8ab1e7a6 caffe::VideoDataLayer<>::DataLayerSetUp()
*** SIGSEGV (@0x20) received by PID 2524 (TID 0x7f4a8b1e3800) from PID 32; stack trace: ***
    @     0x7f4a88bc64b0 (unknown)
    @     0x7f4a8ab1e7a6 caffe::VideoDataLayer<>::DataLayerSetUp()
    @     0x7f4a8ab2af33 caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @     0x7f4a8a9f7247 caffe::Net<>::Init()
    @     0x7f4a8a9f8ad1 caffe::Net<>::Net()
    @     0x7f4a8abd225a caffe::Solver<>::InitTrainNet()
    @     0x7f4a8abd3667 caffe::Solver<>::Init()
    @     0x7f4a8abd3a0a caffe::Solver<>::Solver()
    @     0x7f4a8abc1b43 caffe::Creator_SGDSolver<>()
    @           0x40c21a train()
    @           0x4088e8 main
    @     0x7f4a88bb1830 __libc_start_main
    @           0x4091b9 _start
    @                0x0 (unknown)
Segmentation fault (core dumped)


Operating system: ubuntu 16.04
Compiler: gcc 5.4.0
CUDA version (if applicable): 8.0
CUDNN version (if applicable): 5.1
```

**Comment by chuckcho** [comment] 2017-08-03 14:12
@MengXinChengXuYuan from what i see, video loading didn't seem right (`0 video chunks`)

**Comment by MengXinChengXuYuan** [comment] 2017-08-03 15:10
@chuckcho sorry but I thought it's the problem of random seed which makes it can't read the videos correctly
And it's the path of the c3d_ucf101_train_split1.txt not set correctly in fact
Sorry for asking question like this but I can`t delete this issue
And thanks for your help

**Comment by chuckcho** [comment] 2017-09-21 03:02
@MengXinChengXuYuan have you fixed this issue?

**Comment by chuckcho** [comment] 2017-09-21 17:26
Closing as I can't reproduce this

**Closed by chuckcho** 2017-09-21 17:26 UTC
